# Vendor Package Manifest
# This is the single source of truth for the package
# Generated by OVPS on {{GENERATED_DATE}}

package:
  vendor: "{{VENDOR_NAME}}"
  product: "{{PRODUCT_NAME}}"
  version: "{{VERSION}}"
  description: "{{DESCRIPTION}}"

# Minimum system requirements
requirements:
  docker_version: "20.10.0"
  disk_space_gb: 10
  memory_gb: 4
  architectures:
    - amd64
    - arm64

# Container images included in this package
containers:
  # List container images with their files
  # - name: "vendor/image-name"
  #   file: "containers/{{VERSION}}/image-name.tar.gz"
  #   tag: "{{VERSION}}"

# Services defined in docker-compose.yaml
services:
  # List services that will be started
  # - name: "service-name"
  #   container: "vendor/image-name"
  #   ports:
  #     - "8080:80"

# Data volumes for persistence
volumes:
  # - name: "data-volume"
  #   path: "data/persistent/volume-name"
  #   description: "Persistent storage for service data"

# Health check endpoints
healthchecks:
  # - service: "service-name"
  #   type: "http"
  #   endpoint: "http://localhost:8080/health"
  #   timeout_seconds: 30

# Package metadata
metadata:
  created: "{{GENERATED_DATE}}"
  generator: "ovps"
  generator_version: "1.0.0"
